spring.application.name=demo
spring.data.mongodb.uri=mongodb://localhost:27017/logisticsDB
server.port=8080

# H2 Analytics DB
spring.datasource.url=jdbc:h2:mem:analyticsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
