spring.application.name=demo
spring.data.mongodb.uri=mongodb://localhost:27017/logisticsDB
server.port=8080

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Batch Settings
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
